language: ruby
sudo: false
cache: bundler

rvm:
  - 2.4.1
  - 2.3.4
  - 2.2.7
  - 2.1.10
  - 1.9.3

gemfile:
  - Gemfile
  - test/gemfiles/minimum_versions

matrix:
  include:
    - rvm: 1.8.7
      gemfile: test/gemfiles/1.8.7-compatible
    - rvm: 1.8.7
      gemfile: test/gemfiles/1.8.7-minimum_versions
